name: protac
channels:
  - anaconda
  - schrodinger
  - omnia
  - conda-forge
  - salilab
  - defaults
dependencies:
  - babel=2.7.0
  - biopython=1.73
  - numpy=1.16.4
  - numpy-base=1.16.4
  - numpydoc=0.9.1
  - openbabel=2.4.1
  - openforcefield=0.4.0
  - openmm=7.3.1
  - openmmtools=0.18.2
  - openmoltools=0.8.3
  - pandas=0.24.2
  - parmed=3.2.0
  - pymol=2.3.2
  - python=3.7.3
  - rdkit=2019.03.2

